### ISSUE TITLE
[Bug] Server Tick Crash

### ISSUE THREAD

**Issue by verlixis** [ThePoultryMan/Crops-Love-Rain#1]
Minecraft 1.18.1
Mods:
techreborn 5.1.0
Crops-Love-Rain 1.2.0
croptopia 1.8.3
Fabric-API 46.4

Issue:
When raining, Cabbage crops supported by Greenhouse controllers may grow beyond stage 7 which causes the crash.
Quoted from the log:
`Caused by: java.lang.IllegalArgumentException: Cannot set property class_2758{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7]} to 8 on Block{croptopia:cabbage_crop}, it is not an allowed value`

**Comment by ThePoultryMan** [comment]
This issue probable happens with other crops as well, but it should still be easy to fix.

**Comment by ThePoultryMan** [comment]
A fixed version (1.2.1) has been released to all platforms.
