### ISSUE TITLE
Can be marked as 1.19.3 compatible

### ISSUE THREAD

**Issue by sternschnaube** [ThePoultryMan/Crops-Love-Rain#2]
Hello, I was testing the mod right now and everything looks fine.
Could you please specify in the description, what types of plants / crops are affected?

And this is manipulating only the tick speed of the plants, right - and not the day counter?

Thanks already 😊

**Comment by ThePoultryMan** [comment]
I have marked the mod as 1.19.3 compatible. Once I release the next version, I will update the description to include the various plants affected.

Regarding your question, the mod works by adding an extra chance to grow each time they tick. This means the day counter is completely unaffected
