### ISSUE TITLE
Update to 1.20.1

### ISSUE THREAD

**Issue by Lafolie** [ThePoultryMan/Crops-Love-Rain#3]
Hi, are there any plans to update the mod for 1.20? Really like this one, would be great to keep using it!

**Comment by ThePoultryMan** [comment]
I am currently working on the update now. The update should be out soon, and I'll close this issue once it is out.

**Comment by Lafolie** [comment]
Thanks!

**Comment by ThePoultryMan** [comment]
The update has been released. You can find it on GitHub and Modrinth. (It is still under review on CurseForge)

**Comment by ThePoultryMan** [comment]
It was literally just approved by CurseForge, and can now be downloaded there.

**Comment by Lafolie** [comment]
Thank you!
