### ISSUE TITLE
mod not working on 1.20.1?

### ISSUE THREAD

**Issue by DadoIrie** [ThePoultryMan/Crops-Love-Rain#4]
since the crops won't grow faster on my modpack I've made a instance only with Crops Love Rain (and ofc Fabric API) and even set `rainGrowthSpeed = 10000, useRainGrowthSpeed = true` & `useGeneralSpeedCrops = true, cropsCustomSpeed = 10000` and wheat just won't grow faster

https://mclo.gs/AjTDJIW (even tho the logs not saying anything, but also showing that no other mods where present)

EDIT: btw its on fabric

**Comment by Fyoncle** [comment]
Any news on this issue?

**Comment by ThePoultryMan** [comment]
Because I cannot reproduce this issue, on any version, I am going to close this issue.
Version 2.1.0, for 1.21, `debug mode` can be enabled through the mod settings. This might help to diagnose future problems.

**Comment by Fyoncle** [comment]
> Because I cannot reproduce this issue, on any version, I am going to close this issue. Version 2.1.0, for 1.21, `debug mode` can be enabled through the mod settings. This might help to diagnose future problems.

Maybe an incompatibility? for my modlist, i use Elysium Days 5.0.0 modpack.
