### ISSUE TITLE
Ambiguous crop growth speed number

### ISSUE THREAD

**Issue by teleheel** [ThePoultryMan/Crops-Love-Rain#5]
The config options for growth speed states that a lower number equals faster growth. Do you think you could add a short line specifying how the number relates to e.g. the vanilla growth speed? Or maybe change the number to be a percentage/multiple of the vanilla growth speed, i.e. setting the config option to 1.5 would result in crops growing 1.5 times faster than normally when it rains.

**Comment by ThePoultryMan** [comment]
A comment has been added to clarify what the setting means as of 1.5.0.
