### ISSUE TITLE
Mod is REALLY broken. [1.20.1 Fabric]

### ISSUE THREAD

**Issue by Fyoncle** [ThePoultryMan/Crops-Love-Rain#7]
https://github.com/ThePoultryMan/Crops-Love-Rain/issues/4
This issue was true.
![image](https://github.com/user-attachments/assets/5116f0a6-1fa3-4638-a18c-0dd0c0e481e3)
In completely vanilla testing with only Mod Menu and Crops Love Rain, by setting the growth speed to 10000, nothing grows faster than default.

You closed it saying its a mod incompatibility but there is no mods that can conflict with it, that is no sense
![image](https://github.com/user-attachments/assets/75ba9ff3-69c3-4d50-90d9-82270d05300e)

**Comment by ThePoultryMan** [comment]
I'm not sure what the problem is. On the most recent version (2.2.0) this is not an issue. However, version 1.4.0 is no longer supported.

**Comment by Fyoncle** [comment]
> I'm not sure what the problem is. On the most recent version (2.2.0) this is not an issue. However, version 1.4.0 is no longer supported.

... That's painful
